const PRIMARY = '#959595'
const SECONDARY = '#075595'
const BACKGROUND = '#F9F9F9'
const BLACK = '#000000'
const GRAY = '#E9ECFF'
const LIGHT_GRAY = '#E4E4E4'
const DARK_GRAY = '#F4F5F9'
const TEXT = '#221F1F'
const TEXT_LIGHT = '#969BA0'
const LIGHT_GREEN = '#00da34'
const WHITE = '#FFFFFF'

export default {
  PRIMARY,
  SECONDARY,
  BACKGROUND,
  BLACK,
  GRAY,
  LIGHT_GRAY,
  DARK_GRAY,
  WHITE,
  TEXT,
  TEXT_LIGHT,
  LIGHT_GREEN,
}
